### ISSUE TITLE
Testing on the Magento nginx configurations

### ISSUE THREAD

**Issue by danielc1234** [magenx/nginx-config#3]
Hi,

I was wondering if you have done extensive testing with the magento nginx configuration in the way of optimization and best practices?

Thanks

**Comment by magenx** [comment]
please explain

**Comment by danielc1234** [comment]
Meaning, have you thoroughly tested these settings to be the most optimized for running magento?

**Comment by magenx** [comment]
yes, 
do you see any issues?

**Comment by danielc1234** [comment]
I have not tried it yet. I was just curious cause I am planning on using some of the suggestions you have.

One thing I noticed is, you do not have your rewrites setup to handle the /index.php/. An example is: www.example/com/index.php so that it rewrites 301 to www.example.com/   ?
or
www.example.com/index.php/category_page to www.example.com/category_page

I think this is very important to have for SEO purposes.
I do not see an area with that information in configuration.
